# Gateway heartbeat sensor and RFID binary sensors
binary_sensor:
  - platform: mqtt
    name: "RF24 Gateway Status"
    state_topic: "gateway/heartbeat"
    payload_on: "on"
    payload_off: "off"
    device_class: connectivity

  - platform: mqtt
    name: "RFID Reader 1 Access"
    state_topic: "rf24/rfid1"
    value_template: "{{ value_json.authorized }}"
    payload_on: "true"
    payload_off: "false"
    device_class: "lock"

  - platform: mqtt
    name: "RFID Reader 1 Connection"
    state_topic: "rf24/rfid1"
    value_template: "{{ value_json.connected | default('false') }}"
    payload_on: "true"
    payload_off: "false"
    device_class: "connectivity"

# RFID Sensors
sensor:
  # RFID Reader 1
  - platform: mqtt
    name: "RFID Reader 1"
    state_topic: "rf24/rfid1"
    value_template: "{{ value_json['user_name'] | default('None') }}"
    json_attributes_topic: "rf24/rfid1"
    json_attributes_template: >-
      {
        "card_id": "{{ value_json.card_id }}",
        "authorized": {{ value_json.authorized | default('false') }},
        "battery": {{ value_json.batt | default(0) }},
        "battery_percentage": {{ value_json.batt_perc | default(0) }},
        "last_retry_count": {{ value_json.retries | default(0) }},
        "signal_quality": {{ value_json.signal | default(0) }}
      }
    device_class: "id"
    state_class: "measurement"

  # Battery level sensor
  - platform: mqtt
    name: "RFID Reader 1 Battery"
    state_topic: "rf24/rfid1"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt_perc }}"
    device_class: "battery"
    state_class: "measurement"

  # RF24 Signal Quality Indicator
  - platform: mqtt
    name: "RFID Reader 1 Signal"
    state_topic: "rf24/rfid1"
    unit_of_measurement: "%"
    value_template: "{{ value_json.signal | default(0) }}"
    device_class: "signal_strength"
    state_class: "measurement"

  # Transmission Retry Counter
  - platform: mqtt
    name: "RFID Reader 1 Retries"
    state_topic: "rf24/rfid1"
    value_template: "{{ value_json.retries | default(0) }}"
    state_class: "measurement"

# Automations
automation:
  # Unauthorized access attempts
  - alias: "RFID Unauthorized Access Attempt"
    trigger:
      platform: mqtt
      topic: "rf24/rfid1"
      value_template: "{{ value_json.authorized == 'false' }}"
    action:
      - service: notify.notify
        data:
          title: "Unauthorized RFID Access Attempt"
          message: "User '{{ trigger.payload_json.user_name }}' (Card ID: {{ trigger.payload_json.card_id }}) attempted access"

  # Communication issues
  - alias: "RFID Communication Problems"
    trigger:
      platform: mqtt
      topic: "rf24/rfid1"
      value_template: "{{ value_json.retries > 2 }}"
    action:
      - service: notify.notify
        data:
          title: "RFID Communication Issues"
          message: >
            High retry count ({{ trigger.payload_json.retries }}) detected.
            Signal quality: {{ trigger.payload_json.signal }}%
            Battery level: {{ trigger.payload_json.batt_perc }}%

  # Low signal quality alert
  - alias: "RFID Low Signal Quality"
    trigger:
      platform: mqtt
      topic: "rf24/rfid1"
      value_template: "{{ value_json.signal < 50 }}"
    action:
      - service: notify.notify
        data:
          title: "RFID Signal Quality Alert"
          message: >
            Low signal quality detected ({{ trigger.payload_json.signal }}%).
            Consider checking antenna position or interference sources.
