
# Gateway heartbeat sensor
binary_sensor:
  - platform: mqtt
    name: "RF24 Gateway Status"
    state_topic: "gateway/heartbeat"
    payload_on: "on"
    payload_off: "off"
    device_class: connectivity

# RFID Sensors
sensor:
  # RFID Reader 1
  - platform: mqtt
    name: "RFID Reader 1"
    state_topic: "rf24/rfid1"
    value_template: "{{ value_json.card_id }}"
    json_attributes_topic: "rf24/rfid1"
    json_attributes_template: >-
      {
        "authorized": {{ value_json.authorized }},
        "battery": {{ value_json.batt }},
        "battery_percentage": {{ value_json.batt_perc }}
      }
    device_class: "id"
    state_class: "measurement"

  # Battery level sensor
  - platform: mqtt
    name: "RFID Reader 1 Battery"
    state_topic: "rf24/rfid1"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt_perc }}"
    device_class: "battery"
    state_class: "measurement"

# Authorization status
binary_sensor:
  - platform: mqtt
    name: "RFID Reader 1 Access"
    state_topic: "rf24/rfid1"
    value_template: "{{ value_json.authorized }}"
    payload_on: "true"
    payload_off: "false"
    device_class: "lock"

# Optional: Automations for unauthorized access attempts
automation:
  - alias: "RFID Unauthorized Access Attempt"
    trigger:
      platform: mqtt
      topic: "rf24/rfid1"
      value_template: "{{ value_json.authorized == 'false' }}"
    action:
      - service: notify.notify
        data:
          title: "Unauthorized RFID Access Attempt"
          message: "Card ID {{ trigger.payload_json.card_id }} attempted access"
